server:
  port: 8081

spring:
  application:
    name: customer-service

  # ========== CONFIGURACIÓN JPA + JDBC ==========
  datasource:
    url: jdbc:mysql://localhost:3306/customer_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: bank_user
    password: bank_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ========== CONFIGURACIÓN JPA/HIBERNATE ==========
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: false
    show-sql: false

  # ========== CONFIGURACIÓN SQL SCRIPTS ==========
  sql:
    init:
      mode: never

# ========== LOGGING ==========
logging:
  level:
    com.bank.customer: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# ========== SWAGGER/OPENAPI CONFIGURATION ==========
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false

# ========== INFORMACIÓN DE LA API ==========
info:
  app:
    name: Customer Service
    description: Microservicio para gestión de clientes bancarios
    version: 1.0.0